#pragma once
void MenuChinh();
void Menu1();
void Menu2();
void Menu5();
int NgayTrongThang(int thang, int nam);
void XuatNgayHetHan(int ngay, int thang, int nam);
void XemThongTinDocGia(char MaDocGia[10], char HoTen[20], char CMND[10], char NgaySinh[10], char Email[50], char DiaChi[30], int ngay, int thang, int nam, int gioitinh);
void MenuChonThongTin();
int ThemDocGia();
void XemDanhSachTatCaDocGia(int dem);
void SuaThongTin(int n, int m);
void TimDocGiaTheoCMND();
int XoaThongTin(int m);
int KiemTraChuoiCon(char a[20], char b[20]);
void TimDocGiaTheoTen(char TenTim[10]);
void XemDanhSachSach(char MaSach[10], char TenSach[30], char TacGia[20], char NXB[30], int NamXB, int TheLoai, int GiaSach, int SoQuyen);
void XemDanhSachTatCaSach(int dem);
int ThemSach();
void MenuChonThongTinSach();
void SuaThongTinSach(int n, int m);
int XoaSach(int m);
void XemThongTinSach(char MaSach[10], char TenSach[30], char TacGia[20], char NXB[30], int TheLoai, int GiaSach, int NamXB, int SoQuyen);
void TimKiemSachTheoISBN();
void TimKiemSachTheoTen(char TenTim[30]);
void NhapMaDocGia(int dem);
void NhapMaSach(int dem);
void XuatNgayTraDuKien(int ngay, int thang, int nam);
int NhapSoQuyenSach(int dem);
int PhieuMuonSach(int SoDocGia, int SoQuyenSach);
int KiemTraTinhDungSaiCuaNgay(int ngay, int thang, int nam);
int KiemTraNgayTreHan(int ngaymuon, int thangmuon, int nammuon, int ngaytra, int thagntra, int namtra);
void PhieuTraSach(int SoDocGia, int SoQuyenSach);
int SoDG();
int SoSachCoTrongThuVien();
void DanhSachISBNMuon(int SoDocGia, int SoQuyenSach);
void SachTheoTheLoai();
void DocGiaTheoGioiTinh();
int SachDuocMuon(int SoDocGia, int SoQuyenSach);
int NguoiTreHan(int SoDocGia);
int GiaSach1(char MaS[10]);
void MenuThongKe();
int KiemTraTrungMaDG(int SoDocGia, char MaDoGia[10]);
int KiemTraTrungMaS(int SoQuyenSach, char MaSa[10]);
void GanGiaTriTamp(int SoQuyenSach);
void GanGiaTri(int SoDocGia, int SoQuyenSach);
void XemThongTinDocGiaThuK(int i);
int ThoiGianHetHanTheThuVienCuaDocGiaK(int i);
